### ISSUE TITLE
How to collect k8s container log file(not stdout and stderr )

### ISSUE THREAD

**Issue by fcfangcc** [kaasops/vector-operator#140]
How to collect k8s  pod/container log files (not stdout and stderr )?

Like app write logs to  container path  **/app/logs/test.log**

I try to use kubernetes_logs, but it seems to only collect logs from **/var/log/pods/**

k8s container runtime: containerd

```yaml
apiVersion: observability.kaasops.io/v1alpha1
kind: ClusterVectorPipeline
metadata:
  labels:
    app.kubernetes.io/instance: vector
  name: test
  namespace: ilogtail
spec:
  sources:
    app-logs:
      type: kubernetes_logs
      extra_label_selector: "app.cloudr.com/instance=test"
      # include_paths_glob_patterns:
      #   - "**/*.log"
  sinks:
    console-debug:
      inputs:
        - app-logs
      type: console
      encoding:
        codec: json
```
