### ISSUE TITLE
Collect logs from a pod

### ISSUE THREAD

**Issue by MatheusMorozetti** [kaasops/vector-operator#141]
I want collect logs for all pods in my namespace sessaw with label app=seesaw. I'm using  extra_label_selector: "app=seesaw" for collect this but, I'm getting a error:
```
    x unknown field `extra_label_selector`, expected one of `include`,
    `exclude`, `file_key`, `start_at_beginning`, `ignore_checkpoints`,
    `read_from`, `ignore_older_secs`, `max_line_bytes`, `host_key`, `data_dir`,
    `offset_key`, `glob_minimum_cooldown_ms`, `fingerprint`, `ignore_not_found`,
    `message_start_indicator`, `multi_line_timeout`, `multiline`,
    `max_read_bytes`, `oldest_first`, `remove_after_secs`, `line_delimiter`,
    `encoding`, `acknowledgements`, `log_namespace`

    in `sources.netbox-audit-axiom-source`
    
```
My vector-pipeline:
    
      ```
          apiVersion: observability.kaasops.io/v1alpha1
      kind: ClusterVectorPipeline
      metadata:
        labels:
          app.kubernetes.io/instance: vector
        name: netbox-audit
        namespace: seesaw
      spec:
        sources:
          axiom-source:
            include:
              - /var/log/netbox/plugins.log
            type: file
            extra_label_selector: "app=seesaw"
        sinks:
          axiom-sink:
            token: "key"
            dataset: netbox-dev
            type: axiom
            inputs:
              - axiom-source
      ```
  
  There is a way to collet log from a file only pods with label app=seesaw?

**Comment by zvlb** [comment]
Hi.
`ClusterVectorPipeline` - not namespace-scope resource.

I think you need to use [VectorPipeline](https://github.com/kaasops/vector-operator/blob/main/docs/design.md#vectorpipeline) if you want create VP in namespace, where pod exist

**Comment by zvlb** [comment]
And you use source type - `file`.
You need use `kubernetes_logs`& You can find example [here](https://github.com/kaasops/vector-operator/blob/main/docs/quick-start.md#deploy-minimal-vectorpipeline-cr-for-get-log-spamer-logs)

**Comment by MatheusMorozetti** [comment]
I guess VectorPipeline is porpose to collect event pod log, not from a file. I'm using this example to collet logs from a file:
https://github.com/kaasops/vector-operator/blob/main/docs/logs-from-file.md

But, I don't want collect logs from all pods, I need

**Comment by zvlb** [comment]
`VectorPipeline` and `ClusterVectorPipeline` work the same way. The only difference is that `VectorPipeline` is limited to the namespace where it is defined. (You cannot use VectorPipeline, defined in namespace a, to collect logs from pods defined in namespace b).

For your case, try:
```
apiVersion: observability.kaasops.io/v1alpha1
kind: VectorPipeline
metadata:
  labels:
    app.kubernetes.io/instance: vector
  name: netbox-audit
  namespace: seesaw
spec:
  sources:
    axiom-source:
        type: kubernetes_logs
        extra_label_selector: "app=seesaw"
  sinks:
    axiom-sink:
      token: "key"
      dataset: netbox-dev
      type: axiom
      inputs:
        - axiom-source
```
With this VP you get all logs (stdout and stderr) from pods with label `app=seesaw` in namespace `seesaw`.

P.S. May be you need install `url` field for axiom sink. [Docs](https://vector.dev/docs/reference/configuration/sinks/axiom/#url)

**Comment by MatheusMorozetti** [comment]
Great! There is a way to change log directory from /var/log/pods? I want insert into /var/log/netbox?

I serach this [article](https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/) and found a option: include_paths_glob_patterns

I got this error: 

`
    x unknown field `include_paths_glob_patterns`, expected one of
    `extra_label_selector`, `extra_namespace_label_selector`, `self_node_name`,
    `extra_field_selector`, `auto_partial_merge`, `data_dir`,
    `pod_annotation_fields`, `namespace_annotation_fields`,
    `node_annotation_fields`, `exclude_paths_glob_patterns`, `read_from`,
    `ignore_older_secs`, `max_read_bytes`, `max_line_bytes`,
    `fingerprint_lines`, `glob_minimum_cooldown_ms`,
    `ingestion_timestamp_field`, `timezone`, `kube_config_file`,
    `delay_deletion_ms`, `log_namespace`

    in `sources.seesaw-netbox-audit-axiom-source``
    
    Seems I can't use the attribute

**Comment by zvlb** [comment]
I'm not sure about this field and how it works.
May be vector developers add this field in last releases. If you deploy vector-operator with helm, try to update vector to last release:
```
vector-operator:
  vector:
    enable: true
    agent:
      image: "timberio/vector:0.37.1-debian"
```
Or you can update CRD vector manualy)

**Comment by MatheusMorozetti** [comment]
I saw in the requirements of vector-operator the default volume hostPath  is /var/log/pods

`This source requires read access to the /var/log/pods directory. When run in a Kubernetes cluster this can be provided with a [hostPath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) volume.`

I need change this hostPath to /var/log/netbox, I tried create volumes in the operator
```
volumes:
  - hostPath:
      path: /var/log/netbox
      type: DirectoryOrCreate
    name: netbox-logs
```

But the application still collecting logs from /var/log/pods

**Comment by MatheusMorozetti** [comment]
I tried to your suggest to download other image and download CRD manually, but my VP still catching filePath /var/log/pods

I search all atributes that VP accept [here](https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#kube_config_file)

I didn't find a filePath to change log collector

`sources:
  my_source_id:
    type: kubernetes_logs
    auto_partial_merge: true
    data_dir: /var/local/lib/vector/
    delay_deletion_ms: 60000
    exclude_paths_glob_patterns:
      - "**/exclude/**"
    extra_field_selector: metadata.name!=pod-name-to-exclude
    extra_label_selector: my_custom_label!=my_value
    extra_namespace_label_selector: my_custom_label!=my_value
    fingerprint_lines: 1
    glob_minimum_cooldown_ms: 60000
    ignore_older_secs: 600
    include_paths_glob_patterns:
      - "**/include/**"
    ingestion_timestamp_field: .ingest_timestamp
    kube_config_file: /path/to/.kube/config
    max_line_bytes: 32768
    max_read_bytes: 2048
    oldest_first: true
    read_from: beginning
    rotate_wait_secs: 9223372036854776000
    self_node_name: ${VECTOR_SELF_NODE_NAME}
    timezone: local`

**Comment by MatheusMorozetti** [comment]
I solve this case, using ClusterVectorPipeline, here my file.yaml to collect any logs from hostPath /log

```
apiVersion: observability.kaasops.io/v1alpha1
kind: ClusterVectorPipeline
metadata:
  name: vector-logs
spec:
  sinks:
    k8s-audit-sink:
      dataset: netbox_dev
      inputs:
        - k8s-audit
      token: ${AXIOM_TOKEN}
      type: axiom
  sources:
    k8s-audit:
      include:
        - /log
      type: file
```
