### ISSUE TITLE
ClusterVectorPipeline consider add config disabled generate inputs name

### ISSUE THREAD

**Issue by fcfangcc** [kaasops/vector-operator#143]
Now ClusterVectorPipeline add Prefix for all component name and their `inputs`

But  like `prometheus_exporter`sink will binding port to export,  
if 2 ClusterVectorPipeline have `prometheus_exporter`(want same port) will error "error=Resource `tcp 0.0.0.0:9598` is claimed by multiple components ..."

Maybe ClusterVectorPipeline add disabled for Prefix, like
```yaml
apiVersion: observability.kaasops.io/v1alpha1
kind: ClusterVectorPipeline
metadata:
  labels:
    app.kubernetes.io/instance: vector
  name: app-file-logs
spec:
  add_prefix: false

  sinks:
    to-prometheus_exporter:
      inputs:
          - "*_metrics"
      type: prometheus_exporter

  transforms:
    error-logs_metrics:
      type: log_to_metric
      inputs:
        - xxxx
      metrics:
        - type: counter
          field: level
          name: vector_logs_error_counter
```
`to-prometheus_exporter` will  consume  all component match  `*_metrics`(not add prefix) ,now inputs will change to `app-file-logs*_metrics`

Or there are other, graceful ways to support this?
