### ISSUE TITLE
Unsupported source type syslog

### ISSUE THREAD

**Issue by vitorjcorreia** [kaasops/vector-operator#168]
Hello!

I tried to create a vector pipeline with a source type `syslog` but the operator keeps throwing this error:

`2025-01-23T12:27:39Z ERROR Failed to determine pipeline role {"controller": "vectorpipeline", "controllerGroup": "observability.kaasops.io", "controllerKind": "VectorPipeline", "VectorPipeline": {"name":"haproxy-logs"}, "namespace": "", "name": "haproxy-logs", "reconcileID": "383deffe-81ba-4841-b61e-0249ceb3c46d", "Pipeline": "haproxy-logs", "error": "unsupported source type: syslog"}`

My pipeline is configured like this:

```yaml
apiVersion: observability.kaasops.io/v1alpha1
kind: ClusterVectorPipeline
metadata:
  name: haproxy-logs
  namespace: observability
spec:
  sources:
    primary:
      type: syslog
      address: 0.0.0.0:9000
      mode: tcp
  transforms:
    basic:
      type: "remap"
      inputs:
        - primary
  sinks:
    loki:
      type: "console"
      inputs:
        - basic
      endpoint: http://loki-gateway.observability.svc.cluster.local:8080/loki/api/v1/push
```

I checked the operator code and in deed there is no `syslog` declared as source types. Is this on purpose?

https://github.com/kaasops/vector-operator/blob/dda646e5e32a6c1830a85ff7af74a3d9843079d1/internal/config/vector_source_types.go#L3-L43

Any help is appreciated!
