### ISSUE TITLE
Question about VectorPipeline

### ISSUE THREAD

**Issue by metacoma** [kaasops/vector-operator#75]
Hello!

I correctly understand that the vector-operator doesn't support following pipeline at this moment, until the `Vector aggregator support` is not ready?
```yaml
apiVersion: observability.kaasops.io/v1alpha1
kind: VectorPipeline
metadata:
  name: tmux-bytestream-kafka
spec:
  sinks:
    kafka:
      bootstrap_servers: mindwm-kafka-bootstrap.kafka:9092
      compression: none
      encoding:
        codec: json
      inputs:
        - tcp
      topic: tmux-pane-bytestream
      type: kafka
  sources:
    tcp:
      mode: tcp
      port: 40000
      type: socket

```
