### ISSUE TITLE
Not able to deploy vector to read logs and send them to clickhouse.

### ISSUE THREAD

**Issue by jaswanthcherukuri1** [kaasops/vector-operator#99]
Hi 
I am trying to deploy vector and send logs to clickhouse. Below is what i have been trying. But I am not able to push logs. 

```
apiVersion: observability.kaasops.io/v1alpha1
kind: ClusterVectorPipeline
metadata:
  name: sample
  namespace: vector-operator
spec:
  sources:
    log_generator:
      type: file
      ignore_older_secs: 60
      include:
        - /var/log/containers/loggen*.log
      read_from: beginning
  sinks:
    clickhouse_vector:
      type: clickhouse
      inputs: 
        - log_generator
      endpoint: <clickhouse_endpoint>
      database: <dbName>
      table: <TableName>
      auth:
        strategy: basic
        user: <USERNAME>
        password: <PAssword>
      skip_unknown_fields: false
```
I have tried using Kind VectorPipeline also But i don't see anything happening. 

And how to see the logs for these crd's as none of the crd's are not creating any pods.

Am i missing something here?

Thanks in Advance.
